version: '3.6'
services:
  db:
    image: postgres:latest
    restart: always
    tty: true
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: NinjaFabricSaleDB
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgres
#      - ./src/main/resources/db/v1_create_attendant_table.sql:/docker-entrypoint-initdb.d/v1_create_attendant_table.sql
    networks:
      - compose-network

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - compose-network

  kafka:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - compose-network

networks:
  compose-network:
    driver: bridge
volumes:
  db:
    driver: local