@startuml

title Diagrama de classes completo

package Controllers #DDDDDD {

    class SellerController{
        
    }
    class ManagerController {}
    class AdministratorController {}

}

package Processors #DDDDDD {

    class SellerProcessor{}
    class ManagerProcessor {}
    class AdministratorProcessor {}

}


package Repositories #DDDDDD {

    class SellerRepository{}
    class ManagerRepository {}
    class AdministratorRepository {}
    
}

SellerController --> SellerProcessor
ManagerController --> ManagerProcessor
AdministratorController --> AdministratorProcessor

SellerProcessor --> SellerRepository
ManagerProcessor --> ManagerRepository
AdministratorProcessor --> AdministratorRepository

@enduml