@startuml

title Cadastro de usuários

actor Manager
participant SellerController
participant SellerRepository
database SalesDb

activate Manager

Manager -> SellerController : saveSeller(seller : Seller)

    activate SellerController

    SellerController -> SellerRepository : save(seller : Seller)

        activate SellerRepository

        SellerRepository --> SellerController : true

            activate SalesDb

            SellerRepository -> SalesDb

            deactivate SalesDb

        deactivate SellerRepository

    SellerController --> Manager : seller : Seller

    deactivate SellerController




deactivate Manager

@enduml